channels:
  - conda-forge
dependencies:
  - python=3.11
  - bokeh
  - cartopy
  - cftime
  - fsspec
  - hvplot
  - dask
  - distributed
  - panel
  - datashader
  - geoviews
  - xarray
  - zarr
  - netcdf4==1.6.0
  - s3fs
  - cf_xarray
  - intake-xarray
  - metpy
  - requests
  - jupyter-panel-proxy
  - nbgitpuller
