channels:
  - conda-forge
dependencies:
  - python=3.10
  - cartopy
  - fsspec
  - hvplot
  - holoviews
  - panel
  - datashader
  - geoviews
  - xarray
  - zarr
  - netcdf4
  - cf_xarray
  - intake-xarray
  - metpy
  - requests
  - jupyter-panel-proxy
  - nbgitpuller
